# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.9
    ####   DO NOT CHANGE THIS DIRECTORY ELSE NOTHING WILL WORK DUE TO THE GOLANG workspace dyanmic
    working_directory: /go/src/queroquitar
    steps:
      - checkout
      - run: go test queroquitar/pixelify
  compile:
    docker:
      - image: circleci/golang:1.9
    ####   DO NOT CHANGE THIS DIRECTORY ELSE NOTHING WILL WORK DUE TO THE GOLANG workspace dyanmic
    working_directory: /go/src/queroquitar
    steps:
      - checkout
      - run: go install queroquitar/pixelify
      - run: mkdir bin
      - run: cp $GOPATH/bin/* bin
      - run: ls -la bin
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - run: docker build . -t gcr.io/kubetest-180915/queroquitar
      - run: echo $GCLOUD_SERVICE_KEY > kubetest-180915.json
      - run: gcloud auth activate-service-account --key-file kubetest-180915.json
      - run: sudo gcloud docker -- push gcr.io/kubetest-180915/queroquitar
      - run: curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.14.0/bin/linux/amd64/kubectl
      - run: sudo chmod a+x kubectl
      - run: sudo mv kubectl /sbin/
      - run: gcloud config set project kubetest-180915
      - run: gcloud container clusters get-credentials standard-cluster-1 --zone us-east1-c --project kubetest-180915
      - run: kubectl set image deployment/pixel-generator app=gcr.io/kubetest-180915/queroquitar:latest
workflows:
  version: 2
  build_deploy:
    jobs:
    - test
    - compile:
        requires:
          - test
    - deploy:
        requires:
          - compile