apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pixel-generator
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: pixel-generator
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 40