apiVersion: v1
kind: Service
metadata:
  name: pixel-generator
  namespace: default
  labels:
    app: micro
spec:
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: micro
  type: NodePort